CREATE TABLE IF NOT EXISTS google_calendar_connections (
  user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  google_email varchar(255) NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  expires_at timestamp NOT NULL,
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS google_calendar_meetings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entity_kind varchar(8) CHECK (entity_kind IS NULL OR entity_kind IN ('lead', 'task')),
  entity_id integer,
  google_event_id varchar(255) NOT NULL,
  title varchar(255) NOT NULL,
  meet_url text,
  calendar_url text,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL CHECK (ends_at > starts_at),
  attendees jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_google_calendar_meetings_entity
  ON google_calendar_meetings (entity_kind, entity_id, starts_at);

CREATE INDEX IF NOT EXISTS idx_google_calendar_meetings_user
  ON google_calendar_meetings (user_id, starts_at);
