import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRoleToContact1764993629329 implements MigrationInterface {
    name = 'AddRoleToContact1764993629329'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "fkmadpnoo432ddwgfkx3kw2k3nd"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "fk5nvk2pja04n1pbiyk1xn7739l"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_contact_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "leads_type_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "fkbtix0l86q73wgky011177lmba"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "companies_type_check"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "role" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "companies_pkey"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."companies_type_enum" AS ENUM('DESIGN', 'HOA', 'GENERAL_CONTRACTOR', 'SUPPLIER', 'SUBCONTRACTOR', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "type" "public"."companies_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "service_id"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "service_id" integer`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "is_customer" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "notes" jsonb`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "Contacts_pkey"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "contacts" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "notes" jsonb`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "company_id" integer`);
        await queryRunner.query(`ALTER TABLE "project_type" DROP CONSTRAINT "project_type_pkey"`);
        await queryRunner.query(`ALTER TABLE "project_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "project_type" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_type" ADD CONSTRAINT "PK_2a06e25261f5e8eb431d3683931" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP CONSTRAINT "lead_clickup_mapping_pkey"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD CONSTRAINT "PK_6f1aa896ab30eb20e7e07203260" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP CONSTRAINT "uke1369sq5dp2syjbs6xk9dtkev"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "lead_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD CONSTRAINT "UQ_e6eb3953d9c99844a0ca86a18bf" UNIQUE ("lead_id")`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "lead_number"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "lead_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "clickup_task_id"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "clickup_task_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "clickup_task_url"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "clickup_task_url" character varying`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "Leads_pkey"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "start_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."leads_status_enum" AS ENUM('NOT_EXECUTED', 'COMPLETED', 'IN_PROGRESS', 'LOST', 'POSTPONED', 'PERMITS')`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "status" "public"."leads_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "lead_type"`);
        await queryRunner.query(`CREATE TYPE "public"."leads_lead_type_enum" AS ENUM('CONSTRUCTION', 'PLUMBING', 'ROOFING')`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "lead_type" "public"."leads_lead_type_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "notes" jsonb`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "contact_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "contact_id" integer`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "type" integer`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_pkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_status"`);
        await queryRunner.query(`CREATE TYPE "public"."projects_project_status_enum" AS ENUM('NOT_EXECUTED', 'IN_PROGRESS', 'COMPLETED', 'LOST', 'POSTPONED')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_status" "public"."projects_project_status_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "invoice_status"`);
        await queryRunner.query(`CREATE TYPE "public"."projects_invoice_status_enum" AS ENUM('PAID', 'PENDING', 'NOT_EXECUTED')`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "invoice_status" "public"."projects_invoice_status_enum"`);
        // Delete projects without lead_id before adding NOT NULL constraint
        await queryRunner.query(`DELETE FROM "projects" WHERE "lead_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "lead_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_services" DROP CONSTRAINT "company_services_pkey"`);
        await queryRunner.query(`ALTER TABLE "company_services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company_services" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_services" ADD CONSTRAINT "PK_25fc94c7e4cfcf84d772c76c68e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_b53945f3dfe982678bfeb5e1b4f" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD CONSTRAINT "FK_e6eb3953d9c99844a0ca86a18bf" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_517db338cbbdc2dcffd8dea4c99" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_b1027d153d0546e8460bbaa14e2" FOREIGN KEY ("type") REFERENCES "project_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_f92749a9dcdd54f83bdde8edfd5" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_f92749a9dcdd54f83bdde8edfd5"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_b1027d153d0546e8460bbaa14e2"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_517db338cbbdc2dcffd8dea4c99"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP CONSTRAINT "FK_e6eb3953d9c99844a0ca86a18bf"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_b53945f3dfe982678bfeb5e1b4f"`);
        await queryRunner.query(`ALTER TABLE "company_services" DROP CONSTRAINT "PK_25fc94c7e4cfcf84d772c76c68e"`);
        await queryRunner.query(`ALTER TABLE "company_services" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "company_services" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "company_services" ADD CONSTRAINT "company_services_pkey" PRIMARY KEY ("id")`);
        // Delete projects without lead_id before adding NOT NULL constraint
        await queryRunner.query(`DELETE FROM "projects" WHERE "lead_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "lead_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "invoice_status"`);
        await queryRunner.query(`DROP TYPE "public"."projects_invoice_status_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "invoice_status" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "project_status"`);
        await queryRunner.query(`DROP TYPE "public"."projects_project_status_enum"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "project_status" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "type" bigint`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "contact_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "contact_id" bigint`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "lead_type"`);
        await queryRunner.query(`DROP TYPE "public"."leads_lead_type_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "lead_type" text`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."leads_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "status" text`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "start_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "Leads_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "clickup_task_url"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "clickup_task_url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "clickup_task_id"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "clickup_task_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "lead_number"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "lead_number" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP CONSTRAINT "UQ_e6eb3953d9c99844a0ca86a18bf"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "lead_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD CONSTRAINT "uke1369sq5dp2syjbs6xk9dtkev" UNIQUE ("lead_id")`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP CONSTRAINT "PK_6f1aa896ab30eb20e7e07203260"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lead_clickup_mapping" ADD CONSTRAINT "lead_clickup_mapping_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "project_type" DROP CONSTRAINT "PK_2a06e25261f5e8eb431d3683931"`);
        await queryRunner.query(`ALTER TABLE "project_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "project_type" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_type" ADD CONSTRAINT "project_type_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "company_id"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "company_id" bigint`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "contacts" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "Contacts_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "companies" ALTER COLUMN "is_customer" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "service_id"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "service_id" bigint`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."companies_type_enum"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "type" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "companies_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "companies_type_check" CHECK (((type IS NULL) OR ((type)::text = ANY ((ARRAY['REGULAR'::character varying, 'CONTRACTOR'::character varying, 'DESIGN'::character varying, 'HOA'::character varying, 'GENERAL_CONTRACTOR'::character varying, 'SUPPLIER'::character varying, 'SUBCONTRACTOR'::character varying, 'OTHER'::character varying])::text[]))))`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "fkbtix0l86q73wgky011177lmba" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_type_fkey" FOREIGN KEY ("type") REFERENCES "project_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "leads_contact_id_fkey" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "fk5nvk2pja04n1pbiyk1xn7739l" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "fkmadpnoo432ddwgfkx3kw2k3nd" FOREIGN KEY ("service_id") REFERENCES "company_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
