export enum LeadStatus {
  NEW_LEAD = 'NEW_LEAD',
  CONTACTED = 'CONTACTED',
  ESTIMATING_PREPARING_PROPOSAL = 'ESTIMATING_PREPARING_PROPOSAL',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  FOLLOW_UP = 'FOLLOW_UP',
  WON = 'WON',
  LOST = 'LOST',
}
